# Generated by Django 6.0 on 2026-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='My Shop', max_length=150)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('receipt_footer', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Shop settings',
            },
        ),
    ]
